### ISSUE TITLE
Kappa meaning

### ISSUE THREAD

**Issue by edcarruth** [isrish/VMM#1]
Hi! I just started using your code and it's working great for the most part on my data! Thanks for sharing.

I just have a quick question - how can I interpret the obj.Kappa value coming from fitVMM_CEM? For my data, it is a value in the 10s to 100s. I expected 0<=obj.Kappa<=1 based on the von Mises Fisher distribution. Is there a scaling factor or some other way to interpret this value? Any help on this would be great!

**Edit**
After looking at it some more, it seems maybe if I divide by 1,000, I'll get the result I'm after? Still unsure though.

**Comment by isrish** [comment]
Kappa κ is the so-called concentration parameter. It characterize how strongly the unit vectors drawn accordingly to the VM distribution `f(x| µ, κ) `  are concentrated about the mean direction `µ' .  Larger values of  κ imply stronger concentration about the mean direction. In particular when κ = 0, the distribution  reduces to the uniform density on 'S^d−1', and as κ → ∞,  it tends to a point density.

**Comment by edcarruth** [comment]
Thank you, that helps. I just thought it was supposed to range from 0 to 1, with 1 representing a point density. Thanks again!
