### ISSUE TITLE
rbar update

### ISSUE THREAD

**Issue by stachu86** [isrish/VMM#2]
I think that according to "Clustering on the unit hypersphere using von Mises-Fisher distributions" the update of _rbar_ in _Maximization_ function missing a scaling of _N_.

I suspect that
`rbar  = normMu/W(k);`
shoud be
`rbar  = normMu/(W(k)*N);`
according to _Algorithm 1_ in the referred paper.

**Comment by isrish** [comment]
You might have missed it, the scaling is already done before computing rbar. 
e.g Line 198 in fitVMM_CEM.m

**Comment by stachu86** [comment]
I'm aware of that. Take a look at the algorithm in the [paper](http://www.jmlr.org/papers/volume6/banerjee05a/banerjee05a.pdf). When calculating _rbar_ we have to multiply _W_ by _N_ to ignore the effect of  the scaling (dividing _W_ by _N_) you mentioned.

**Comment by isrish** [comment]
Thanks for pointing it out. I will cross check with the paper. I wonder how it affects the K parameter which is also a numerical approximation in the M-step.

**Comment by stachu86** [comment]
I'm also a little confused about regularization of _Kappa_
`Kappa = Kappa + 1/Regularize;` in fitVMM_EM.m
vs
`Kappa(k) = max((rbar*D - rbar^3)/(1-rbar^2),Regularize);` in fitVMM_CEM.m
